### Spring-Kotlin-Captcha API Tests

### Variables
@baseUrl = http://localhost:8081

### Get Captcha Configuration
# Returns the current captcha configuration (difficulty levels)
GET {{baseUrl}}/captcha/config
Accept: application/json

### Generate Text Captcha with Background
# Generates a new text CAPTCHA image with background image
# The token is returned in the X-Captcha-Token header
# @name textCaptchaWithBgResponse
GET {{baseUrl}}/captcha/text?difficultyLevel=MEDIUM&useBackgroundImage=true
Accept: image/png

> {%
    client.global.set("token", response.headers.valueOf("X-Captcha-Token"))
 %}

### Generate Math Captcha
# Generates a new math CAPTCHA image with specified difficulty and background image
# The token is returned in the X-Captcha-Token header
# @name mathCaptchaResponse
GET {{baseUrl}}/captcha/math?difficultyLevel=MEDIUM&useBackgroundImage=true
Accept: image/png

> {%
    client.global.set("token", response.headers.valueOf("X-Captcha-Token"))
 %}

### Generate Pattern Captcha with Background
# Generates a new pattern CAPTCHA image with background image
# The token is returned in the X-Captcha-Token header
# @name patternCaptchaWithBgResponse
GET {{baseUrl}}/captcha/pattern?difficultyLevel=MEDIUM&useBackgroundImage=true
Accept: image/png

> {%
    client.global.set("token", response.headers.valueOf("X-Captcha-Token"))
 %}

### Generate Audio Captcha with Medium Difficulty
# Generates a new audio CAPTCHA with medium difficulty
# The token is returned in the X-Captcha-Token header
# @name audioCaptchaMediumResponse
GET {{baseUrl}}/captcha/audio?difficultyLevel=MEDIUM
Accept: audio/wav

> {%
    client.global.set("token", response.headers.valueOf("X-Captcha-Token"))
 %}

### Validate Text Captcha
# Validates a text CAPTCHA input against the token
# Replace 'your-captcha-answer' with the actual answer to the captcha
POST {{baseUrl}}/captcha/validate
Content-Type: application/x-www-form-urlencoded

captchaInput=your-captcha-answer&token={{token}}
