spring:
  application:
    name: Spring-Kotlin-Captcha
  thymeleaf:
    cache: false

# Server configuration
server:
  port: 8081
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false

# Captcha configuration
captcha:
  secretKey: ThisIsASecretKey1234567890123456
  expirationMinutes: 10
  #captchaType: TEXT
  #captchaType: MATH
  captchaType: AUDIO
  #captchaType: PATTERN
  difficultyLevel: HARD
  #difficultyLevel: EASY, MEDIUM, HARD
